site_name: Tuan Hiep Pham
site_url: https://hieppt.github.io/
nav:
  - Home: index.md
  - About: about.md
theme: readthedocs


# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
    permalink: true

plugins:
  - search
  - roamlinks
